# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/.github
# If you want to suggest a change, please open a PR or issue in that repository

enhancement: ['enhancement/*', 'feature/*']
documentation: ['*docs*', 'docs/*', 'doc/*']
bug: ['bug/*', 'fix/*']
dependency-update: ['dep/*', 'dependency/*', 'dependency-update/*']
auto-update: 'update/*'