# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/sbt-ci
# If you want to suggest a change, please open a PR or issue in that repository

enhancement: ['enhancement/*', 'feature/*']
documentation: ['docs/*', 'doc/*']
breaking-change: ['breaking/*', 'break/*']
bug: ['bug/*', 'fix/*']
tests: ['test/*', 'tests/*']
dependency-update: ['dep/*', 'dependency/*', 'dependency-update/*']
scala-steward: ['update/*']
'autorebase:opt-in': ['dep/*', 'dependency/*', 'dependency-update/*', 'update/*']
