# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/sbt-ci
# If you want to suggest a change, please open a PR or issue in that repository

name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "⚠️ Breaking changes"
    label: ":warning: breaking"
  - title: "🚀 Features"
    label: ":rocket: feature"
  - title: "📘 Documentation"
    label: ":blue_book: documentation"
  - title: "🐛 Bug Fixes"
    label: ":beetle: bug"
  - title: "📈 Dependency updates"
    label: ":chart_with_upwards_trend: dependency-update"
exclude-labels:
  - "build"
template: |
  ## What's changed

  $CHANGES
autolabeler:
  - label: ":rocket: feature"
    branch:
      - "/enhancement\/.+/"
      - "/feature\/.+/"
      - "/feat\/.+/"
  - label: ":blue_book: documentation"
    files:
      - "*.md"
    branch:
      - "/docs\/.+/"
      - "/documentation\/.+/"
      - "/doc\/.+/"
  - label: ":warning: breaking"
    branch:
      - "/breaking\/.+/"
      - "/break\/.+/"
  - label: ":beetle: bug"
    branch:
      - "/bug\/.+/"
      - "/fix\/.+/"
  - label: ":lipstick: style"
    branch:
      - "/style\/.+/"
      - "/format\/.+/"
  - label: ":package: refactor"
    branch:
      - "/refactor\/.+/"
  - label: ":broom: cleaning"
    branch:
      - "/remove\/.+/"
      - "/clean\/.+/"
  - label: ":wrench: build"
    files:
      - "project/**"
      - "build.sbt"
    branch:
      - "/build\/.+/"
  - label: ":test_tube: test"
    branch:
      - "/test\/.+/"
      - "/tests\/.+/"
      - "/testing\/.+/"
  - label: ":chart_with_upwards_trend: dependency-update"
    branch:
      - "/update\/.+/"
      - "/dep\/.+/"
      - "/dependency\/.+/"
      - "/dependency-update\/.+/"
      - "/develop"