pull_request_rules:
  - name: automatic merge for master when CI passes and at least 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=test
      - base=master
      - label=auto-update
    actions:
      merge:
        method: merge