pull_request_rules:
  - name: automatic merge for auto-update PRs
    conditions:
      - label=auto-update
    actions:
      merge:
        method: merge
  - name: automatic merge for scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=test
    actions:
      merge:
        method: merge