addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.4.31")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.8")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.9.7")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.2.1")
addSbtPlugin("com.alejandrohdezma"       % "sbt-fix"        % "0.1.1")
