addSbtPlugin("com.alejandrohdezma"       % "sbt-fix"        % "0.2.6")
addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.2")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"     % "5.4.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.10")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"       % "2.1.1")
