name: Auto merge github-actions bot updates

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  merge-me:
    runs-on: ubuntu-latest
    steps:
      - name: Merge github-actions PR
        if: contains({{github.event.pull_request.body}}, 'semver-patch')
        uses: ridedott/merge-me-action@v1.1.3
        with:
          GITHUB_LOGIN: github-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}