name: Update changelog

on:
  push:
    tags: v**

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude-labels: duplicate,question,invalid,wontfix,auto-update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update CHANGELOG.md
          title: '[auto] Update CHANGELOG.md'
          labels: auto-update
          branch: auto-update-changelog
          body: Update CHANGELOG.md with information from latest release
