name: Update changelog

on:
  push:
    tags: v**

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout project
      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update changelog
        uses: EndBug/add-and-commit@v2
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "Update changelog"
          path: "."
          pattern: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
