# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/sbt-ci
# If you want to suggest a change, please open a PR or issue in that repository

name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  label-pr:
    name: Add labels to PR
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  spread-settings:
    name: Spread repository settings
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip ci')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        if: github.event_name == 'push'
        uses: actions/checkout@v2.3.4
      - name: Spread settings
        uses: mattsb42/repo-manager@v1
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  auto-merge:
    runs-on: ubuntu-latest
    name: Auto-merge succesfull Scala Steward PRs
    needs: [label-pr, test]
    steps:
      - name: Automerge Scala Steward PRs
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.body, 'Scala Steward')
        uses: ridedott/merge-me-action@v1.8.61
        with:
          GITHUB_LOGIN: alejandrohdezma
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Run "sbt ci-test" on JDK ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk:
          - adopt:1.8
          - adopt:1.11
          - adopt:1.15
    steps:
      - name: Checkout project (pull-request)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout project (master)
        if: github.event_name == 'push'
        uses: actions/checkout@v2.3.4
      - name: Setup Coursier
        uses: laughedelic/coursier-setup@v1
        with:
          jvm: ${{ matrix.jdk }}
          apps: sbt
      - name: Enable Coursier cache
        uses: coursier/cache-action@v5
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
      - name: Setup yq
        run: sudo snap install yq
      - name: Run pre-conditions
        run: test -f .github/actions.yml && eval "$(yq r .github/actions.yml -D "true" pre.ci)" || true
      - name: Run scalafmt on Scala Steward PRs
        if: github.event.pull_request.user.login == 'alejandrohdezma' && contains(github.event.pull_request.body, 'Scala Steward')
        run: sbt fix || sbt "scalafmtAll; scalafmtSbt" || true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Run formatter/linter
      - name: Run generateCiFiles on Scala Steward PRs
        if: github.event.pull_request.user.login == 'alejandrohdezma' && contains(github.event.pull_request.body, 'Scala Steward')
        run: sbt generateCiFiles
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Generate new CI files
      - name: Run checks
        run: sbt ci-test
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - name: Run post-conditions
        run: test -f .github/actions.yml && eval "$(yq r .github/actions.yml -D "true" post.ci)" || true
