name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v1
      name: Checkout project
    - uses: olafurpg/setup-scala@v2
      name: Setup Scala
    - run: csbt "all scalafmtCheckAll scalafmtSbtCheck"
      name: Run scalafmt
    - run: csbt "scalafixAll --check"
      name: Run scalafix
    - run: csbt test
      name: Run tests