name: Formatters & Tests

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v7
      - name: Run scalafmt
        run: sbt "all scalafmtCheckAll scalafmtSbtCheck"
      - name: Run scalafix
        run: sbt "scalafixAll --check"
      - name: Compile documentation
        run: sbt mdoc
      - name: Run tests
        run: sbt test
      - name: Run scripted tests
        run: sbt scripted
        env:
          GITHUB_TOKEN: "this_should_not_be_used"
