name: Formatters & Tests

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v7
      - name: Run checks
        run: sbt ci-test
