# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/.github
# If you want to suggest a change, please open a PR or issue in that repository

name: Formatters & Tests

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v7
      - name: Run checks
        run: sbt ci-test
