name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout project
      - uses: olafurpg/setup-scala@v2
        name: Setup Scala
      - run: csbt "all scalafmtCheckAll scalafmtSbtCheck"
        name: Run scalafmt
      - run: csbt "scalafixAll --check"
        name: Run scalafix
      - run: csbt test
        name: Run tests