# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/.github
# If you want to suggest a change, please open a PR or issue in that repository

name: Update documentation

on:
  release:
    types: [published]

jobs:
  documentation:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          ref: master
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup Scala
        uses: olafurpg/setup-scala@v7
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Setup github-changelog-generator
        run: gem install github_changelog_generator -v 1.15.0
      - name: Generate documentation
        run: sbt ci-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOWNLOAD_INFO_FROM_GITHUB: true
      - name: Generate changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
        run: |
              github_changelog_generator \
                --user ${repo%/*} \
                --project ${repo#*/} \
                --token $GITHUB_TOKEN \
                --exclude-labels "duplicate,question,invalid,wontfix,auto-update,auto-changelog,auto-documentation" \
                --configure-sections \
              '{
                "breaking": {
                  "prefix": "⚠️ **Breaking changes**",
                  "labels": ["breaking-change"]
                },
                "enhancement": {
                  "prefix": "🚀 **Features**",
                  "labels": ["enhancement"]
                },
                "documentation": {
                  "prefix": "📘 **Documentation**",
                  "labels": ["documentation"]
                },
                "bug": {
                  "prefix": "🐛 **Bug Fixes**",
                  "labels": ["bug"]
                },
                "dependency": {
                  "prefix": "📈 **Dependency updates**",
                  "labels": ["dependency-update", "scala-steward"]
                }
              }'
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.3
        with:
          commit_message: 'Update documentation, changelog and other files [skip ci]'