name: Update documentation

on:
  push:
    branches: master

jobs:
  documentation:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v2
      - name: Generate documentation
        run: csbt mdoc
        env:
          RELEASE: true
      - name: Update documentation
        run: |
          mv target/mdoc/*.md .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m 'Update documentation files' || echo "No changes to documentation files"
          git push "https://alejandrohdezma:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:master
