name: Update documentation

on:
  push:
    branches: master
    tags: v**

jobs:
  documentation:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup Scala
        uses: olafurpg/setup-scala@v7
      - name: Generate documentation
        run: sbt ci-docs
        env:
          DOWNLOAD_INFO_FROM_GITHUB: true
      - name: Update documentation
        uses: EndBug/add-and-commit@v3
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "Update documentation files"