name: Update documentation

on:
  push:
    branches: master
    tags: v**

jobs:
  documentation:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup Scala
        uses: olafurpg/setup-scala@v7
      - name: Generate documentation
        run: sbt ci-docs
        env:
          DOWNLOAD_INFO_FROM_GITHUB: true
      - name: Create Documentation Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update documentation and other files
          title: 'Update documentation and other files'
          labels: auto-update,documentation
          branch: auto-update-docs
          body: Update documentation and other files with latest changes.
      - name: Merge Documentation Pull Request
        if: env.PULL_REQUEST_NUMBER != null
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ env.PULL_REQUEST_NUMBER }}
          method: merge