name: Release

on:
  push:
    branches: master
    tags: v**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout project
      - uses: olafurpg/setup-scala@v7
        name: Setup Scala
      - uses: olafurpg/setup-gpg@v2
        name: Setup GPG
      - run: sbt ci-release
        name: Release new version
        env:
          RELEASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
