name: Release

on:
  push:
    branches: master
    tags: v**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout project
      - uses: olafurpg/setup-scala@v2
        name: Setup Scala
      - uses: olafurpg/setup-gpg@v2
        name: Setup GPG
      - run: csbt mdoc ci-release
        name: Release new version
        env:
          RELEASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - run: mv target/mdoc/*.md .
        name: Move generated markdown files
      - uses: stefanzweifel/git-auto-commit-action@v2.5.0
        name: Update markdown files
        with:
          branch: master
          file_pattern: '*.md'
          commit_message: Update markdown files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
