# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/.github
# If you want to suggest a change, please open a PR or issue in that repository

name: Scala Steward

on:
  schedule:
    - cron:  '0 5 * * 1,3,5'
  repository_dispatch:
    types: [scala-steward]

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: alejandrohdezma/scala-steward-action@v1
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          gpg-secret-key: ${{ secrets.GPG_SCALA_STEWARD }}
